
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebServiceImplementation", targetNamespace = "http://jaxwsservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebServiceImplementation {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "myGreetingMessage", targetNamespace = "http://jaxwsservice.com/", className = "client.MyGreetingMessage")
    @ResponseWrapper(localName = "myGreetingMessageResponse", targetNamespace = "http://jaxwsservice.com/", className = "client.MyGreetingMessageResponse")
    @Action(input = "http://jaxwsservice.com/MyWebServiceImplementation/myGreetingMessageRequest", output = "http://jaxwsservice.com/MyWebServiceImplementation/myGreetingMessageResponse")
    public String myGreetingMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
